liip_imagine:
 driver: "gd"
 resolvers:
     default:
         web_path: ~

 filter_sets:
     cache: ~
     product:
         quality: 100
         filters:
             thumbnail: { size: [900, 900], mode: outbound }

     qrcode:
         quality: 80
         filters:
             thumbnail: { size: [300, 300], mode: outbound }