vich_uploader:
  db_driver: orm

  mappings:
    products:
      uri_prefix: /images/products
      upload_destination: '%kernel.project_dir%/public/images/products'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

    qr_code_images:
      uri_prefix: /images/qrcodes
      upload_destination: '%kernel.project_dir%/public/images/qrcodes'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer